#!/bin/bash
########################
# This converts AS_* csv
# into ip_ranges csv
########################
RADB_QUERY(){
        COMPANY=$1
        ASNUM=$2
        shift;
        echo 'Querying WHOIS for' $ASNUM
        whois -h whois.radb.net -- "-i origin $ASNUM" | grep ^route | while read -r ip; do
			ip=${ip//[[:blank:]]/}
			ip=${ip#"route"}
			ip=${ip#"6:"}
			ip=${ip#":"}
			ip=${ip//[[:blank:]]/}
			echo "$ip belongs to $COMPANY, adding to record"
            echo "$COMPANY,$ip" >> ip_ranges_asn_only.csv
        done
}


INPUT=$1
OLDIFS=$IFS
IFS=','
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
while read f1 f2
do
	echo "Company: $f1"
	echo "ASN: $f2"
	RADB_QUERY $f1 $f2
done < $INPUT
IFS=$OLDIFS
