#!/bin/bash
####################################
# Takes csv file of ASNs as input
# This converts AS_* csv
# and queries 3 of the
# RIRs to build the 
# ranges dataset (ip_ranges.csv)
####################################
RADB_QUERY(){
        COMPANY=$1
        ASNUM=$2
        shift;
        echo 'Querying RADB for' $ASNUM
        whois -h whois.radb.net -- "-i origin $ASNUM" | grep ^route | while read -r ip; do
			ip=${ip//[[:blank:]]/}
			ip=${ip#"route"}
			ip=${ip#"6:"}
			ip=${ip#":"}
			ip=${ip//[[:blank:]]/}
			echo "$ip belongs to $COMPANY, adding to record"
            echo "$COMPANY,$ip" >> ip_ranges.csv
        done
}
RIR_QUERY(){
        COMPANY=$1
        RIR=$2
        shift;
        echo "Querying $RIR for $COMPANY"
        whois -h whois.$RIR.net $COMPANY | grep ^inet | while read -r ip; do
			ip=${ip//[[:blank:]]/}
			ip=${ip#"inetnum"}
			ip=${ip#"inet6num:"}
			ip=${ip#":"}
			ip=${ip//[[:blank:]]/}
			echo "$ip belongs to $COMPANY, adding to record"
			echo "$COMPANY,$ip" >> ip_ranges.csv
        done
}


# currently leaving out ARIN and LACNIC because of specifics of their query structure
RIRS=( "apnic" "ripe" "afrinic" )


# pull in ASN csv and execute all queries together
INPUT=$1
OLDIFS=$IFS
IFS=','
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
while read f1 f2
do
	echo "Company: $f1"
	echo "ASN: $f2"
	RADB_QUERY $f1 $f2
	for r in "${RIRS[@]}"
	do
	    RIR_QUERY $f1 $r
	done
done < $INPUT
# IFS=$OLDIFS